services:
  experiencer-web:
    image: ghcr.io/vincentlaucsb/experiencer:latest
    restart: unless-stopped
    networks:
      proxy-net:
        aliases:
          - experiencer-web

networks:
  proxy-net:
    external: true
